stages:
- build
- test
- deploy
- Trigger-cross-projects

build:linux:
  stage: build
  tags:
    - linux
  image: condaforge/mambaforge:latest
  before_script:
    - apt update -yq && apt -yq install build-essential
  script:
    - ./tools/build.sh
  artifacts:
    paths:
      - bld-dir/

build:windows:
  stage: build
  tags:
    - win
  script:
    - .\tools\build.bat
  artifacts:
    paths:
      - bld-dir/

build:osx:
  stage: build
  tags:
    - osx
  script:
    - ./tools/build.sh
  artifacts:
    paths:
      - bld-dir/

test:linux:
  stage: test
  tags:
    - linux
  image: condaforge/mambaforge:latest
  before_script:
    - apt update -yq
    - apt install -yq procps wget git git-lfs
  script:
    - source activate base
    - conda config --add channels "file://`pwd`/bld-dir"
    # for tttrlib
    - conda config --add channels tpeulen
    - mamba install python tttrlib nose scipy
    - git clone https://gitlab.peulen.xyz/tpeulen/tttr-data --depth 1
    - |
      cd test
      nosetests

deploy:conda:
  stage: deploy
  image: condaforge/mambaforge:latest
  tags:
    - linux
  dependencies:
    - build:linux
    - build:windows
    - build:osx
  before_script:
    - git submodule update --init --recursive --remote
  script:
    - ./tools/deploy.sh

# Downstream projects
scikit-fluorescence:
  stage: Trigger-cross-projects
  trigger: skf/scikit-fluorescence

