name: fit2x

channels:
  - tpeulen
  - tpeulen/label/nightly
  - defaults

dependencies:
  - python 3.7.*
  - cmake
  - swig 3.0.12.*
  - setuptools
  - numpy
  - nose
  - anaconda-client
  - conda-build
  - mkl
  - tttrlib >=0.20.0
