{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..
#  git_url: ..

build:
  number: 0
  detect_binary_files_with_prefix: True  # [not win]

requirements:
  build:
    - python {{ python }}
    - numpy
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pkg-config   # [not win]
    - swig
    - ninja
    - cmake
    - make         # [linux]
    - doxygen
  host:
    - python {{ python }}
    - setuptools
    - numpy
    - boost-cpp
    - tttrlib
  run:
    - python {{ python }}
    - boost-cpp
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('tttrlib') }}
    - llvm-openmp # [osx]

test:
  imports:
    - fit2x

about:
  home: https://github.com/fluorescence-tools/fit2x
  license: {{ data.get('license') }}
  summary: Python bindings for fit2x
  description: |
    fit2x is a C++ MLE fitting library including Python bindings for MFD
    data.

extra:
  recipe-maintainers:
    - tpeulen
