{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  #  path: ..
  git_url: ..

build:
    number: 0
    string: py{{ python }}

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    - doxygen
    - git
  build:
    - python {{ python }}
    - numpy
    - cmake
    - swig
    - boost 1.67.0.* [py < 38]
    - boost 1.71.0.* [py >= 38]
    - tttrlib {{ tttrlib }}
    - llvm-openmp # [osx]
  run:
    - python {{ python }}
    - numpy
    - llvm-openmp # [osx]
    - tttrlib {{ tttrlib }}
    - boost 1.67.0.* [py < 38]
    - boost 1.71.0.* [py >= 38]
    - libboost 1.71.0.* [py >= 38]
    - libboost 1.67.0.* [py < 38]

test:
  imports:
    - fit2x

about:
  home: https://github.com/fluorescence-tools/fit2x
  license: {{ data.get('license') }}
  summary: Python bindings for fit2x
  description: |
    fit2x is a C++ MLE fitting library including Python bindings for MFD
    data.
  doc_url: https://fluorescence-tools.github.io/fit2x/

extra:
  recipe-maintainers:
    - tpeulen
