{% set PY_VER_MAJOR = PY_VER[0] %}
{% set PY_VER_MINOR = PY_VER[2] %}
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  #  path: ..
  git_url: ..

build:
    number: 0
    string: py{{ PY_VER_MAJOR }}{{ PY_VER_MINOR }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - swig
    - cmake
    - python {{ python }}
    - boost {{ boost }}
    - numpy
    - setuptools
    - tttrlib >=0.0.20
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('tttrlib', max_pin='x.x.x') }}
    - {{ pin_compatible('boost', max_pin='x.x.x') }}
    - llvm-openmp # [osx]

about:
  home: https://github.com/fluorescence-tools/fit2x
  license: {{ data.get('license') }}
  summary: Python bindings for fit2x
  description: |
    fit2x is a C++ MLE fitting library including Python bindings for MFD
    data.

extra:
  recipe-maintainers:
    - tpeulen
