{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  #  path: ..
  git_url: ../..

build:
    number: 0
    string: py{{ python }}np{{ CONDA_NPY }}boost{{ boost }}hdf5{{ hdf5 }}

requirements:
  host:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - setuptools
    - doxygen
    - git
  build:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - cmake
    - swig {{ swig }}
    - boost {{ boost }}
    - hdf5 {{ hdf5 }}
    - tttrlib {{ tttrlib }}
    - llvm-openmp # [osx]
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - llvm-openmp # [osx]
    - boost {{ boost }} # [win]
    - libboost {{ boost }} # [not win]
    - hdf5 {{ hdf5 }}
    - tttrlib {{ tttrlib }}

test:
  imports:
    - fit2x

about:
  home: https://github.com/fluorescence-tools/fit2x
  license: {{ data.get('license') }}
  summary: Python bindings for fit2x
  description: |
    fit2x is a C++ MLE fitting library including Python bindings for MFD
    data.
  doc_url: https://fluorescence-tools.github.io/fit2x/

extra:
  recipe-maintainers:
    - tpeulen
